services:

  postgres:
    image: postgres:16
    container_name: vaultcore-postgres

    environment:
      POSTGRES_DB: vaultcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  app:
    build: .
    container_name: vaultcore-app

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vaultcore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - "8080:8080"