spring:
  application:
    name: vaultcore-ledger
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vaultcore}
    username: ${SPRING_DATASOURCE_USERNAME:divijmazumdar}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
