ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN email VARCHAR(255) UNIQUE,
ADD COLUMN roles VARCHAR(50) NOT NULL DEFAULT 'USER';

ALTER TABLE users ALTER COLUMN password DROP DEFAULT;
ALTER TABLE users ALTER COLUMN roles DROP DEFAULT;
